// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGif8R64_9E2_W_gnacBQ9wMDY5wn-ojs',
    appId: '1:457040754469:web:5d6ca19b8fbd9e24750ccc',
    messagingSenderId: '457040754469',
    projectId: 'smartanapp-15bd5',
    authDomain: 'smartanapp-15bd5.firebaseapp.com',
    storageBucket: 'smartanapp-15bd5.firebasestorage.app',
    measurementId: 'G-BX9991B1NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa_RxyqzBoFabedpCBLr1xkAZ2vv3qqXs',
    appId: '1:457040754469:android:ec400425ffec5c06750ccc',
    messagingSenderId: '457040754469',
    projectId: 'smartanapp-15bd5',
    storageBucket: 'smartanapp-15bd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVKBuUnumR_O9Mx3ewlgVHx7cQFuNoNT4',
    appId: '1:457040754469:ios:ca489751dc0f3ac7750ccc',
    messagingSenderId: '457040754469',
    projectId: 'smartanapp-15bd5',
    storageBucket: 'smartanapp-15bd5.firebasestorage.app',
    iosBundleId: 'com.example.smartan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVKBuUnumR_O9Mx3ewlgVHx7cQFuNoNT4',
    appId: '1:457040754469:ios:ca489751dc0f3ac7750ccc',
    messagingSenderId: '457040754469',
    projectId: 'smartanapp-15bd5',
    storageBucket: 'smartanapp-15bd5.firebasestorage.app',
    iosBundleId: 'com.example.smartan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGif8R64_9E2_W_gnacBQ9wMDY5wn-ojs',
    appId: '1:457040754469:web:4b982c0542aef520750ccc',
    messagingSenderId: '457040754469',
    projectId: 'smartanapp-15bd5',
    authDomain: 'smartanapp-15bd5.firebaseapp.com',
    storageBucket: 'smartanapp-15bd5.firebasestorage.app',
    measurementId: 'G-ZV66PQJ4E0',
  );
}
